title: <center> Marcel Rocha  </center>
logo: "/images/perfil.png?raw=true"
description: >
  <p align="justify">
    Data Scientist, Msc Engenharia de Materiais e Bsc Nanotecnologia. 
    <b>Data Science</b>,
    <b>Machine Learning</b> <b>Data Analysis</b>.
  </p>
  <a href="https://www.linkedin.com/in/marcel-rocha-nascimento-8185a6148/">Meu LinkedIn</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0
