title: <center> Marcel Rocha Nascimento </center> # your name (or website title) here
logo: "/images/perfil.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <p align="justify">
    Cientista de Dados, Msc Engenharia de Materiais (UFRJ) e Bsc Nanotecnologia (UFRJ).
    <b>Data Science</b>,<b>Machine Learning</b>, <b>Data Analysis</b> e <b>Tecnologia</b>.
  </p>
  <a href="https://www.linkedin.com/in/marcel-rocha-nascimento-8185a6148/">Meu LinkedIn </a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
