title: <center> Marcel Rocha Nascimento</center>
logo: "/images/perfil.png?raw=true"
description: >
  <p align="justify">
    Cientista de dados, Msc Engenharia de Materiais e Bsc Nanotecnologia. 
    <b>Data Science</b>,
    <b>Machine Learning</b>, <b>Data Analysis</b> e <b>Tecnologia</b>.
  </p>
  <a href="https://www.linkedin.com/in/marcel-rocha-nascimento-8185a6148/">Meu LinkedIn</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0
